### ISSUE TITLE
This project is dead?

### ISSUE THREAD

**Issue by mths0x5f** [sjlamerton/wxWebViewChromium#16]

**Comment by sjlamerton** [comment]
No, in fact I expect the wxWebViewChromium backend to be merged into wxWidgets trunk in the near future: 
https://github.com/wxWidgets/wxWidgets/pull/15

**Comment by mths0x5f** [comment]
Oh, that's really good! I was asking just because no commit was done in 8 months and I couldn't figure out the reason for some errors (but I already resolved). Thank you.
