### ISSUE TITLE
Retiring the wxWebViewChromium Repository

### ISSUE THREAD

**Issue by tierra** [sjlamerton/wxWebViewChromium#17]
I believe this repo now represents an outdated version of wxWidgets/wxWidgets#15.

Hopefully that pull request is merged into the main wxWidgets repo soon (possibly within the next week or two), so it would be nice if @steve-lamerton and @hokein could double check that all open issues and pull requests on this repo are addressed in the main pull request, or that they are moved into Trac (for issues), or separate pull requests (for patches) created on the main repo.

In the case of open patches, that would be fine if they waited until wxWidgets/wxWidgets#15 is merged so they have a solid target branch to base changes on. It would just be nice to get this temporary repo removed as soon as we can following the merge so it doesn't continue to confuse developers looking for these changes (and finding the outdated and irrelevant code).

**Comment by sjlamerton** [comment]
Perhaps we could move it back to my personal GitHub? It was originally developed there and it would be a shame to loose some of the history that is present in this but not is the pull request (for example CEF1 support).

**Comment by tierra** [comment]
We can archive it on SF.net similar to how we've done with the old gsoc and wxWebSite repos. They aren't actually available as public downloads anymore, but they're still there if needed.

Certainly feel free to clone it over to your personal account, but I think it causes more confusion than anything right now sitting in the official org.

**Comment by tierra** [comment]
Oh, I guess you mean just transfer the repo (including the issues + PRs). That would be fine too. Want to do that?

**Comment by sjlamerton** [comment]
Yes, that would be my preference, I don't think I have the permissions, can you do it please?

**Comment by tierra** [comment]
Alright, I'll start the transfer now.

**Comment by tierra** [comment]
I guess you still have to do it yourself. I've given you admin access.

**Comment by tierra** [comment]
I guess this can be considered closed now.
