### ISSUE TITLE
Build error on OS X

### ISSUE THREAD

**Issue by IngwiePhoenix** [sjlamerton/wxWebViewChromium#4]
Hello there ^^.

I just wanted to try out this very cool project and tried to build it. After setting up the variables needed, I made an attempt to build it:

``` bash
Ingwie@ingwies-air ~/Downloads/cef_binary_3.1547.1412_macosx64/wxwc/build $ ninja
[2/9] Building CXX object CMakeFiles/wvc.dir/webview_chromium3.cpp.o
FAILED: /Applications/drag0n/drag0n.app/Contents/System/usr/bin/c++   -D_FILE_OFFSET_BITS=64 -D__WXMAC__ -D__WXOSX_COCOA__ -D__WXOSX__ -I/usr/local/include/wx-3.0 -I/Users/Ingwie/Downloads/cef_binary_3.1547.1412_macosx64 -I/usr/local/lib/wx/include/osx_cocoa-unicode-static-3.0 -I/usr/local/include/wx-3.0 -MMD -MT CMakeFiles/wvc.dir/webview_chromium3.cpp.o -MF "CMakeFiles/wvc.dir/webview_chromium3.cpp.o.d" -o CMakeFiles/wvc.dir/webview_chromium3.cpp.o -c ../webview_chromium3.cpp
../webview_chromium3.cpp:15:10: fatal error: 'wx/msw/private.h' file not found
#include <wx/msw/private.h>
         ^
1 error generated.
ninja: build stopped: subcommand failed.
```

I am running wxWidgets 3.0. I also had to

```
sudo cp /usr/local/lib/libwx_osx_cocoau_stc-3.0.a /usr/local/lib/libwx_osx_cocoau_scintilla-3.0.a
```

in order for the build to even start.

Whats the solution here?

Kind regards, Ingwie

**Comment by sjlamerton** [comment]
I am afraid that only Windows is fully supported with this backend at the moment and Linux support is mostly complete. As I don't have easy access to an OSX machine I am unlikely to add support for it but if you would like to do so then please reopen this ticket, I am more than happy to help where I can.

**Comment by IngwiePhoenix** [comment]
I have looked into it, and I might actually fix it.
I also need to fix compatibility with wx3.0 then if i am at it already and if its needed to, but shouldn’t be.
Besides, thanks to wx, its the same method everywhere actually. so it’ll not be very hard. :)

Am Sa. Dez. 28 2013 21:24:04 schrieb Steven Lamerton:
